version: '3'
services:
  webpacker:
    container_name: webpacker
    build: .
    command: bundle exec bin/webpack-dev-server
    ports:
      - "3035:3035"
    depends_on:
      - web
    volumes:
      - .:/app
  web:
    build: .
    # command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
